/**
 * BEHAVIORAL SCHEMA — Internal scoring engine only.
 *
 * Rules:
 * - NEVER API-exposed. Not even to the user themselves (they see derived outputs only).
 * - Read ONLY by internal background jobs (reliability scorer, embedding indexer).
 * - No Fastify route may import from this schema directly.
 * - Database role `scoring_service` is the only role granted SELECT/INSERT here.
 */

import {
  pgSchema,
  uuid,
  text,
  integer,
  real,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";

export const behavioralSchema = pgSchema("behavioral");

// ─── Match Events ─────────────────────────────────────────────────────────────

/**
 * Every state transition in a match is recorded here for audit and scoring.
 */
export const matchEvents = behavioralSchema.table("match_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  matchId: uuid("match_id").notNull(),
  userId: uuid("user_id").notNull(),
  event: text("event", {
    enum: [
      "liked",
      "mutual_match",
      "icebreaker_sent",
      "icebreaker_answered",
      "revealed",
      "first_message",
      "ghosted", // No response after 72h post-reveal
      "unmatched",
      "blocked",
      "reported",
      "collaboration_completed",
      "collaboration_abandoned",
    ],
  }).notNull(),
  metadata: jsonb("metadata"), // Additional event-specific data
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Ghost Log ────────────────────────────────────────────────────────────────

/**
 * Every ghosting incident, used for reliability score deductions.
 */
export const ghostLog = behavioralSchema.table("ghost_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  ghosterId: uuid("ghoster_id").notNull(),
  matchId: uuid("match_id").notNull(),
  ghostType: text("ghost_type", {
    enum: ["post_match", "post_reveal", "post_icebreaker", "event_noshow"],
  }).notNull(),
  scoreDeduction: real("score_deduction").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Reliability Score History ────────────────────────────────────────────────

/**
 * Append-only ledger of every score change. The current score in profiles
 * is always derived from the latest entry here.
 */
export const reliabilityHistory = behavioralSchema.table("reliability_history", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull(),
  previousScore: real("previous_score").notNull(),
  newScore: real("new_score").notNull(),
  delta: real("delta").notNull(),
  reason: text("reason").notNull(), // Human-readable reason
  triggerEvent: text("trigger_event").notNull(), // e.g. "ghost_after_match"
  triggeredBy: uuid("triggered_by"), // Admin or system (null = automated)
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Embeddings ───────────────────────────────────────────────────────────────

/**
 * One embedding vector per user profile.
 * Generated by the MiniLM Python microservice on every profile update.
 * Stored as a float array; queried via pgvector cosine similarity.
 *
 * Note: The pgvector `vector` type is registered at runtime.
 * We store as real[] here and cast in queries until pgvector Drizzle support
 * is fully stable.
 */
export const embeddingVectors = behavioralSchema.table("embedding_vectors", {
  userId: uuid("user_id").primaryKey(),
  // 384-dimensional MiniLM-L6-v2 vector stored as JSON array
  // Will be migrated to pgvector `vector(384)` type once pgvector Drizzle adapter stabilises
  vector: jsonb("vector").$type<number[]>().notNull(),
  modelVersion: text("model_version").notNull().default("all-MiniLM-L6-v2"),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Moderation Log ───────────────────────────────────────────────────────────

/**
 * Every moderation action taken on a user. Used for pattern detection
 * (repeat offenders) and audit trails.
 */
export const moderationLog = behavioralSchema.table("moderation_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  targetUserId: uuid("target_user_id").notNull(),
  action: text("action", {
    enum: [
      "warning_issued",
      "score_deducted",
      "content_hidden",
      "chat_banned",
      "feature_suspended",
      "shadow_banned",
      "account_suspended",
      "account_banned",
      "badge_revoked",
    ],
  }).notNull(),
  reason: text("reason").notNull(),
  scoreDeduction: real("score_deduction"),
  durationDays: integer("duration_days"), // For temporary bans/suspensions
  performedBy: uuid("performed_by"), // Moderator user_id (null = automated)
  isAutomated: boolean("is_automated").notNull().default(false),
  relatedReportId: uuid("related_report_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Response Time Tracker ────────────────────────────────────────────────────

/**
 * Tracks average response time per user in active chats.
 * A score component for reliability calculation.
 */
export const responseTimeStats = behavioralSchema.table("response_time_stats", {
  userId: uuid("user_id").primaryKey(),
  averageResponseMs: integer("average_response_ms"),
  totalMessagesAnalysed: integer("total_messages_analysed").notNull().default(0),
  lastUpdatedAt: timestamp("last_updated_at", { withTimezone: true }).notNull().defaultNow(),
});
